### ISSUE TITLE
Better Understanding/Documenting DID Resolution

### ISSUE THREAD

**Issue by dleve123** [microsoft-healthcare-madison/health-wallet-demo#26]
@jmandel  – 👋 – thanks for this awesome example app!

### Context

I'm working with a group that's introducing health card functionality into our android application and we're using this codebase as a reference.

In particular, I'm trying to better understand ION DID resolution.

### Understanding

My understanding so far:

- holders need to verify SIOP requests sent from issuers/verifiers to ensure authenticity of entity behind SIOP requests. The entry-point to this verification is `verifyJWS`
  - https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/bf9de724826d157689f0e0dbb3ab8926f6a32990/src/holder.ts#L193

-  `verifyJWS` performs verification by calling the `GET /api/did/:did` endpoint with the full did (e.g. `did:ion:1234#key-id`)
   - https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/bf9de724826d157689f0e0dbb3ab8926f6a32990/src/dids.ts#L15
    - https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/bf9de724826d157689f0e0dbb3ab8926f6a32990/src/dids.ts#L38
    - https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/bf9de724826d157689f0e0dbb3ab8926f6a32990/src/server.ts#L462-L470

This leads us to `resolveDid`:

https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/bf9de724826d157689f0e0dbb3ab8926f6a32990/src/server.ts#L36-L52

It seems like this `resolveDid` implementation is incredibly similar to that implemented in the sidetree codebase itself, which I presume is your motivation in this implementation: 

https://github.com/decentralized-identity/sidetree/blob/master/lib/core/versions/latest/RequestHandler.ts#L234-L244

### Questions

It seems like this mock create operation doesn't actually read or write to the Bitcoin blockchain during resolution (based off of my reading of the sidetree source and playing around with [this resolver](https://resolver.identity.foundation/)), but just automatically returns a DID Document that is verified.

Am I thinking about this correctly? If so, what would a more "production" implementation of DID creation / resolution look like?

I appreciate these sorts of questions are not exactly related to health cards / VCs, but I imagine you might have some context/pointers here!

**Comment by dleve123** [comment]
@jmandel Good chatting yesterday! For the sake of GH issue management, I'll close this out. Per our discussion, I'll find some time to propose some more language on DID resolution and the ramifications of short and long form DIDs.

**Comment by jmandel** [comment]
Thanks -- and sorry I missed the issue notification when you first wrote this; will be great to incorporate your suggested clarifications back into the spec.

**Comment by madaster97** [comment]
@jmandel @dleve123 ,  related question to this. Are the DIDs used by this example representative of [Long Form DID URIs](https://identity.foundation/sidetree/spec/#long-form-did-uris)? 

**DID Format I'm expecting for Long Form**:  `did:METHOD:<did-suffix>:<long-form-suffix-data>`

**DID Format I see from this lib**: `did:METHOD:<did-suffix>?-ion-initial-state=<long-form-suffix-data ?>`

Since the [Health Cards spec](https://healthwallet.cards/) is specifically suggesting Long Form URIs, this library would be a more helpful set of reference implementations if it used those as well! The actual expectation for DIDs is the least clear portion of the spec to me.

**Comment by jmandel** [comment]
You should see the long-form DIDs you expect on the https://github.com/microsoft-healthcare-madison/health-wallet-demo/ branch -- this reflects changes that have been made between sidetree 0.9.1 and 0.12. Since we've been testing Health Carts prototypes from a bunch of organizations, we wanted to avoid churn in our testing environment, so we've been pinned to 0.9.1 until the sidetree spec is finalized next week, and then will upgrade.

**Comment by jmandel** [comment]
(Agreed this churn has been confusing; I'm looking forward to having this nailed down soon!)
